lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
markdown: kramdown 

collections:
  csc418:
    code: CSC418/CSC2504
    name: Computer Graphics
    term: 2020 Summer
    instructor: Sarah Kushner
    output: true

  apm462:
    code: APM462
    name: Nonlinear Optimization
    term: 2020 Summer
    instructor: Jonathan Korman
    output: true

  csc311:
    code: CSC311
    name: Introduction to Machine Learning
    term: 2019 Fall
    instructor: Richard Zemel
    output: true

  csc320:
    code: CSC320
    name: Introduction to Visual Computing
    term: 2019 Fall
    instructor: Yawen Ma
    output: true
  
  csc336:
    code: CSC336 
    name: Numerical Methods
    term: 2019 Fall
    instructor: Kenneth R. Jackson
    output: true
    
  csc373:
    code: CSC373 
    name: Algorithms - Design, Analysis and Complexity
    term: 2019 Winter
    instructor: Francois Pitt
    output: true

  sta303:
    code: STA303 
    name: Methods of Data Analysis II
    term: 2019 Winter
    instructor: Shivon Sue-Chee
    output: true


defaults:
  -
    scope:
      path: ""
    values:
      layout: "notebook"